/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MateriasPrimasRouteImport } from './routes/materias-primas'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasPrimasRoute = MateriasPrimasRouteImport.update({
  id: '/materias-primas',
  path: '/materias-primas',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kits': typeof KitsRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kits': typeof KitsRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kits': typeof KitsRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/kits'
    | '/materias-primas'
    | '/produtos'
    | '/receitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/kits'
    | '/materias-primas'
    | '/produtos'
    | '/receitas'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/kits'
    | '/materias-primas'
    | '/produtos'
    | '/receitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  KitsRoute: typeof KitsRoute
  MateriasPrimasRoute: typeof MateriasPrimasRoute
  ProdutosRoute: typeof ProdutosRoute
  ReceitasRoute: typeof ReceitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias-primas': {
      id: '/materias-primas'
      path: '/materias-primas'
      fullPath: '/materias-primas'
      preLoaderRoute: typeof MateriasPrimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  KitsRoute: KitsRoute,
  MateriasPrimasRoute: MateriasPrimasRoute,
  ProdutosRoute: ProdutosRoute,
  ReceitasRoute: ReceitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
