/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MateriasPrimasRouteImport } from './routes/materias-primas'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CanceladoRouteImport } from './routes/cancelado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as IndexRouteImport } from './routes/index'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasPrimasRoute = MateriasPrimasRouteImport.update({
  id: '/materias-primas',
  path: '/materias-primas',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CanceladoRoute = CanceladoRouteImport.update({
  id: '/cancelado',
  path: '/cancelado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/cancelado': typeof CanceladoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kits': typeof KitsRoute
  '/landing': typeof LandingRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/cancelado': typeof CanceladoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kits': typeof KitsRoute
  '/landing': typeof LandingRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/cancelado': typeof CanceladoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/kits': typeof KitsRoute
  '/landing': typeof LandingRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/produtos': typeof ProdutosRoute
  '/receitas': typeof ReceitasRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura'
    | '/auth'
    | '/cancelado'
    | '/configuracoes'
    | '/kits'
    | '/landing'
    | '/materias-primas'
    | '/produtos'
    | '/receitas'
    | '/sucesso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinatura'
    | '/auth'
    | '/cancelado'
    | '/configuracoes'
    | '/kits'
    | '/landing'
    | '/materias-primas'
    | '/produtos'
    | '/receitas'
    | '/sucesso'
  id:
    | '__root__'
    | '/'
    | '/assinatura'
    | '/auth'
    | '/cancelado'
    | '/configuracoes'
    | '/kits'
    | '/landing'
    | '/materias-primas'
    | '/produtos'
    | '/receitas'
    | '/sucesso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  CanceladoRoute: typeof CanceladoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  KitsRoute: typeof KitsRoute
  LandingRoute: typeof LandingRoute
  MateriasPrimasRoute: typeof MateriasPrimasRoute
  ProdutosRoute: typeof ProdutosRoute
  ReceitasRoute: typeof ReceitasRoute
  SucessoRoute: typeof SucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias-primas': {
      id: '/materias-primas'
      path: '/materias-primas'
      fullPath: '/materias-primas'
      preLoaderRoute: typeof MateriasPrimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancelado': {
      id: '/cancelado'
      path: '/cancelado'
      fullPath: '/cancelado'
      preLoaderRoute: typeof CanceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  CanceladoRoute: CanceladoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  KitsRoute: KitsRoute,
  LandingRoute: LandingRoute,
  MateriasPrimasRoute: MateriasPrimasRoute,
  ProdutosRoute: ProdutosRoute,
  ReceitasRoute: ReceitasRoute,
  SucessoRoute: SucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
